name: payment_bridge
description: All-in-one payment gateway implementation of Razorpay, Paytm etc.
version: 0.0.3
homepage: https://ensorta.com
repository: https://github.com/hsbijarniya/payment_bridge

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.3
  nb_utils: ^5.0.4
  razorpay_flutter: ^1.2.7
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
